initial_state:
  masterVolume: 0.5
  weatherVolume: 0.5
  lifeMode: "on_drone"
  weather: "clear"
  autoRandomActive: false
  autoRandomInterval: 5

buildings:
  - id: 0
    start_x: 2
    width: 7
    bh: 12
    floors: 6
    cols: 3
    type: "zen"
  - id: 1
    start_x: 12
    width: 7
    bh: 18
    floors: 8
    cols: 3
    type: "bass"
  - id: 2
    start_x: 22
    width: 8
    bh: 14
    floors: 7
    cols: 3
    type: "arp"
  - id: 3
    start_x: 34
    width: 11
    bh: 18
    floors: 8
    cols: 4
    type: "pad"
  - id: 4
    start_x: 47
    width: 7
    bh: 13
    floors: 6
    cols: 3
    type: "noise"
  - id: 5
    start_x: 55
    width: 7
    bh: 11
    floors: 5
    cols: 3
    type: "aeolian"
  - id: 6
    start_x: 63
    width: 7
    bh: 17
    floors: 8
    cols: 3
    type: "whole"
  - id: 7
    start_x: 71
    width: 7
    bh: 13
    floors: 6
    cols: 3
    type: "blues"

channels:
  - volume: 0.8
    timbre: "sine"
    scale: "pentatonic_major"
    rootFreq: 130.81
  - volume: 0.8
    timbre: "triangle"
    scale: "phrygian"
    rootFreq: 65.41
  - volume: 0.8
    timbre: "square"
    scale: "dorian"
    rootFreq: 130.81
  - volume: 0.8
    timbre: "triangle"
    scale: "lydian"
    rootFreq: 261.63
  - volume: 0.8
    timbre: "square"
    scale: "pentatonic_minor"
    rootFreq: 440.00
  - volume: 0.8
    timbre: "sine"
    scale: "minor"
    rootFreq: 220.00
  - volume: 0.8
    timbre: "triangle"
    scale: "whole_tone"
    rootFreq: 261.63
  - volume: 0.8
    timbre: "square"
    scale: "blues"
    rootFreq: 523.25

sweeps:
  L_TO_R:
    active: false
    pos: 0
    bpm: 120
    delayTime: 0
    delayFeedback: 0
  R_TO_L:
    active: false
    pos: 79
    bpm: 120
    delayTime: 0
    delayFeedback: 0
  T_TO_B:
    active: false
    pos: 0
    bpm: 120
    delayTime: 0
    delayFeedback: 0
  B_TO_T:
    active: false
    pos: 23
    bpm: 120
    delayTime: 0
    delayFeedback: 0
